server:
  port: 9000
  address: 127.0.0.1

spring:
# JPA properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect      
# MySQL database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/boot
    noAccessToProcedureBodies: true
    username: boot
    password: password
    driverClassName: com.mysql.jdbc.Driver

  security:
    sessions: NEVER
    