debug:
security:
  user:
    password: none
zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000/resource
oauth2:
  sso:
    home:
      secure: false
      path: /,/**/*.html
  client:
    tokenUri: http://localhost:9999/uaa/oauth/token
    authorizationUri: http://localhost:9999/uaa/oauth/authorize
    clientId: acme
    clientSecret: acmesecret
  resource:
    jwt:
      keyUri: http://localhost:9999/uaa/oauth/token_key
logging:
  level:
    org.springframework.security: DEBUG