debug:
security:
  user:
    password: password
zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user
oauth2:
  sso:
    home:
      secure: false
      path: /,/**/*.html
  client:
    tokenUri: http://localhost:9999/uaa/oauth/token
    authorizationUri: http://localhost:9999/uaa/oauth/authorize
    clientId: acme
    clientSecret: acmesecret
  resource:
    userInfoUri: http://localhost:9999/uaa/user
 
logging:
  level:
    org.springframework.security: DEBUG