spring:
  profiles:
   active: development
  freemarker:
   cache: false
  jpa:
   hibernate:
    ddl-auto: create
---

spring:
  profiles: development
# Redis properties
  redis:
   port: 6379
   host: localhost
   pool.maxIdle: 8
   pool.minIdle: 0
   pool.maxActive: 8
   pool.maxWait: -1
# JPA properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect      
# MySQL database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/boot
    noAccessToProcedureBodies: true
    username: boot
    password: password
    driverClassName: com.mysql.jdbc.Driver
# Facebook
  facebook:
    app:
      accessToken: your-facebook-app-access-token
# Google Plus
  gplus:
    app:
      id: your-gplus-app-id.apps.googleusercontent.com



# toggle this to make "trace" endpoint accessible without any security 
endpoints:
  trace:
    sensitive: true

# Zuul properties
zuul:
 routes:
  resource:
    path: /resource/**
    url: http://localhost:9000

security:
  ignored:
    - /**/*.css
    - /**/*.js
    - /images/**
    - /**/facivon.ico

    
#ConnectionPoolSettings
#    testOnBorrow: true
#    validationQuery: select 1 from INFORMATION_SCHEMA.SYSTEM_USERS
#    validationInterval: 30000
#    maxActive: 100
#    maxIdle: 100
#    minIdle: 10
#    initialSize: 0
#    maxWait: 30000
#    testOnReturn: false
#    testWhileIdle: false
#    timeBetweenEvictionRunsMillis: 5000
#    minEvictableIdleTimeMillis: 60000
#    removeAbandoned: false
#    removeAbandonedTimeout: 60
#    logAbandoned: false
